export const FAILED_REQUEST = 'AUTH_FAILED_REQUEST';
export const LOADING_REQUEST = 'AUTH_LOADING_REQUEST';

export const LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';

export const LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED';

export const RESET_STATE = 'AUTH_RESET_STATE';

export const REQUEST_LOADING = 'AUTH_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'AUTH_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'AUTH_REQUEST_FAILED';

export const GET_BOOKINGS_LIST_REQUEST = 'GET_BOOKINGS_LIST_REQUEST';
export const GET_BOOKINGS_LIST_ERROR = 'GET_BOOKINGS_LIST_ERROR';
export const GET_BOOKINGS_LIST_SUCCESS = 'GET_BOOKINGS_LIST_SUCCESS';

// Users
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_ERROR = 'USERS_FETCH_ERROR';
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS';
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS';

// Rooms
export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_FETCH_SUCCESS = 'ROOMS_FETCH_SUCCESS';
export const ROOMS_FETCH_ERROR = 'ROOMS_FETCH_ERROR';
export const ROOMS_CREATE_SUCCESS = 'ROOMS_CREATE_SUCCESS';
export const ROOMS_UPDATE_SUCCESS = 'ROOMS_UPDATE_SUCCESS';
export const ROOMS_DELETE_SUCCESS = 'ROOMS_DELETE_SUCCESS';

// Groups
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUPS_FETCH_SUCCESS = 'GROUPS_FETCH_SUCCESS';
export const GROUPS_FETCH_ERROR = 'GROUPS_FETCH_ERROR';
export const GROUPS_CREATE_SUCCESS = 'GROUPS_CREATE_SUCCESS';
export const GROUPS_UPDATE_SUCCESS = 'GROUPS_UPDATE_SUCCESS';
export const GROUPS_DELETE_SUCCESS = 'GROUPS_DELETE_SUCCESS';

// Approvals
export const APPROVALS_LOADING = 'APPROVALS_LOADING';
export const APPROVALS_FETCH_SUCCESS = 'APPROVALS_FETCH_SUCCESS';
export const APPROVALS_FETCH_ERROR = 'APPROVALS_FETCH_ERROR';
export const APPROVALS_APPROVE_SUCCESS = 'APPROVALS_APPROVE_SUCCESS';
export const APPROVALS_REJECT_SUCCESS = 'APPROVALS_REJECT_SUCCESS';

// My Bookings
export const MY_BOOKINGS_LOADING = 'MY_BOOKINGS_LOADING';
export const MY_BOOKINGS_FETCH_SUCCESS = 'MY_BOOKINGS_FETCH_SUCCESS';
export const MY_BOOKINGS_FETCH_ERROR = 'MY_BOOKINGS_FETCH_ERROR';
export const MY_BOOKINGS_CANCEL_SUCCESS = 'MY_BOOKINGS_CANCEL_SUCCESS';

// Book Room
export const BOOK_ROOM_LOADING = 'BOOK_ROOM_LOADING';
export const BOOK_ROOM_AVAILABLE_ROOMS_SUCCESS = 'BOOK_ROOM_AVAILABLE_ROOMS_SUCCESS';
export const BOOK_ROOM_AVAILABLE_SLOTS_SUCCESS = 'BOOK_ROOM_AVAILABLE_SLOTS_SUCCESS';
export const BOOK_ROOM_SUCCESS = 'BOOK_ROOM_SUCCESS';
export const BOOK_ROOM_ERROR = 'BOOK_ROOM_ERROR';
export const BOOK_ROOM_RESET = 'BOOK_ROOM_RESET';




