export const GET_BOOKINGS_LIST_REQUEST = 'GET_BOOKINGS_LIST_REQUEST';
export const GET_BOOKINGS_LIST_ERROR = 'GET_BOOKINGS_LIST_ERROR';
export const GET_BOOKINGS_LIST_SUCCESS = 'GET_BOOKINGS_LIST_SUCCESS';